server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routh         #路由的ID
          #uri: http://localhost:8001   #匹配后提供服务的路由i地址
          uri: lb://cloud-payment-service
          predicates:                  #断言
            - Path=/payment/get/**     #路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/discovery/**
          # - After=..... 匹配在这个时间之后，类似与开启秒杀功能。
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka