server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
logging:
  level:
    com.atguigu.springcloud.PaymentFeignService: debug